# https://github.com/cncjs/cncjs/blob/master/.travis.yml
# https://github.com/resin-io/etcher/blob/master/.travis.yml
# https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml

# https://docs.travis-ci.com/user/ci-environment/
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/environment-variables/

osx_image: xcode8.1

# permissoes 
sudo: required
dist: trusty
# https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/
# group: edge

language: node_js

os:
  - linux
  - osx

node_js:
  - '6'

# https://docs.travis-ci.com/user/environment-variables/
env:
  global:
    # para o erro em macOS - Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    secure: "eryx7/5CJL5nrB2L1RXQ0XZwmeF5HQJWtp9r5BdoWTHv5FCWFizgRVrb5BhCKrEMHQuDX84iO8ICMKtxUrqGOrghbxSUS+LHyLU3wM48hKx+EWX1fNiKnFq95+QmjTVFJWxokkaN01SW0WcCDILWcZrbO5x5+FdrlYXXHdh5S/40twaFeeVnND2TiJqsEdGj+fRMCmqxZy3CheDTqwIslJ0OMt6QQqefvdAUibhPP193iIljD7+h/TF/zYER1fYi6GST/lAdgNzvQuuXWJAlzBsOstO0v7q6BvPXz7faLL97DrxPjMyriPdUVVyqCOI95+IKHs065k+BHz1VgcYkl+oHwlvjZzn9epEAv2pMld2IR3+MO13A1Z7w8PJQGS38vtHjl2OO5XhK9Pkco+ZFWFkBNvzPMfsYdP3z7o/2/Fo061bfYvNs0ZAvNXFXkcXFT3kWtq4NRV8UtvsxzeUk+RNdmbIPtOwgUydoFUUobKhix2cHo0jvJZy0bZ2DyZNU1rdBFDplkjcdFHeJQirgWZCGZSYHK3S7gNjCDWueLfRRdPxMayHNlRkSAXjdFrF5aTQQw94p569rDveEemHUCuk5J3Krt2NNX/SrEkzUQx8iYHxCgoVRDUGC7U3Amn3QMzl0lQITIzCCxKGaGHqkiSpu65BHMPudvT0CYzou9Qw=" #"GH_TOKEN"

# https://docs.travis-ci.com/user/customizing-the-build/
# https://github.com/travis-ci/travis-ci/issues/1532
branches:
  only:
  - master
  - /^v[0-9]/ # apenas com tags!
  
cache:
  directories:
    - $HOME/.electron

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - gcc-multilib
      - g++-multilib

before_install:
  # http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
  - chmod a+x script/package-name.sh
  - chmod a+x script/package-version.sh

  - git --version
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"

  # https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#os-x
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
    fi

  - npm install -g npm
  - npm --version

#install: travis_wait 40 npm install

after_success:
  - mkdir -p releases
  
  # http://stackoverflow.com/questions/28217556/travis-ci-auto-tag-build-for-github-release
  # deixar desta forma, nao colocar espacos, erro!
  - PACKAGE_NAME=`script/package-name.sh package.json`
  - PACKAGE_VERSION=`script/package-version.sh package.json`
  - RELEASE=${PACKAGE_NAME}-v${PACKAGE_VERSION}
  # - COMMIT_LOG=`git log -1 --format='%ci %H %s'`

  - echo "${RELEASE}"
  # - echo "${COMMIT_LOG}"

  - |
    # build:mac-x64
    if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "osx" ]]; then
      # https://github.com/electron-userland/electron-builder/issues/398
      # security import "scripts/certs/Certum-Code-Signing-CA-SHA2.cer" -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign;
      # https://github.com/electron-userland/electron-osx-sign/issues/83
      # Temporarily Bypass Gatekeeper
      sudo spctl --master-disable;
      sudo spctl --status;

      npm run build:mac-x64;

      ls -al output;
      cp -af "output/mac/${RELEASE}.dmg" "releases/${RELEASE}-mac-x64.dmg";

      ls -al releases/*;
    fi
  - |
    # build:linux-ia32
    if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    
      npm run build:linux-ia32;
    
      ls -al output;
      cp -af "output/${PACKAGE_NAME}_${PACKAGE_VERSION}_i386.deb" "releases/${RELEASE}-linux-i386.deb";
      rm -rf "output/linux-ia32-unpacked";

      ls -al releases;

    fi
  - |
    # build:linux-x64
    if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then

      npm run build:linux-x64;
    
      ls -al output;
      cp -af "output/${PACKAGE_NAME}_${PACKAGE_VERSION}_amd64.deb" "releases/${RELEASE}-linux-amd64.deb";
      rm -rf "output/linux-unpacked";

      ls -al releases;

    fi
 
before_deploy:
  - echo "Deploying to GitHub releases"
# https://github.com/travis-ci/travis-ci/issues/2498
branches:
  only:
    - master   
deploy:
  provider: releases
  api_key:
    # https://docs.travis-ci.com/user/encrypting-files/
    # https://github.com/travis-ci/travis-ci/issues/4154
    # Editing the travis slug in .git/config, as described in #3093, restored my ability to encrypt files.
    secure: "w+erVeQJ8g1jqVBl84CxS4jc+GuYyGWfjlTM3pN+Ma/Z/Ie8MeNhc9SmtcDbbzg+fmjMM2H5OF7kHvDGCnLkHNYLp8CLw8hl04X8HzB2K9ZoxQvchHh+acgZOY1Trif+12qhiVJEkL0oCtBJewwZ77QaBjhZnHsdu24rK3pyUYYbkt6zfudu/HPNUskDR8paoaK7g+5AF8VS6qSXawA50V4ljLyFj2WPWfTfvqMgNTLl60uALyW/K3iFBMu3UgNTX3kUUgn3nt1NIY4XW6lmaTJqKzxLa7giUy/Oj0AHUlG3a/MnfxVVyjjM0RV3ywAVDqQEEIQkh+Z/aGNVQG5W7RVeXTv0ncncy8vzNMKBKbUX2noT25tV66HT/t+qnPQEVYbnfW+q1jr92XpfOZGrU1mhN02ZmMAR/424zJLBY3k9HKDdvu+GRyxmIfvn7YvaAVz27Xh1kULlYCWhdQxYZVD/X3NqhpHZjnJHuNeUHmKtX3dF0Jekx1KGQEEcyJ28gukg780Lrqf0RFSMDRfmbQB7SF96ZBwizowYNtQJ4NYP2lPL9vxi4q76bDkkRqUPgJyYPXz468TvpUxSlYji0Bwp7a25za5W8piudBwZJAOj0woUtZGwkD9BH2uyqOg9pz+Q6C8tjid1pNlAj1sywwOaiXmwDEkkaYrnyWGgpbY="
  file_glob: true
  file:
    - 'releases/*.*'
  overwrite: true
  skip_cleanup: true
  on:
    # https://docs.travis-ci.com/user/deployment
    # https://github.com/travis-ci/travis-ci/issues/6499
    tags: false  # Deploy app only when a tag is applied to the commit
    node: '6'

# https://docs.travis-ci.com/user/notifications    
notifications:
    email: false    